// iOS System Colors
export const colors = {
  white: 'rgb(255, 255, 255)',
  systemGray6Light: 'rgb(242, 242, 247)',
  systemGray5Light: 'rgb(229, 229, 234)',
  systemGray4Light: 'rgb(209, 209, 214)',
  systemGray3Light: 'rgb(199, 199, 204)',
  systemGray2Light: 'rgb(174, 174, 178)',
  systemGray: 'rgb(142, 142, 147)',
  systemGray2Dark: 'rgb(99, 99, 102)',
  systemGray3Dark: 'rgb(72, 72, 74)',
  systemGray4Dark: 'rgb(58, 58, 60)',
  systemGray5Dark: 'rgb(44, 44, 46)',
  systemGray6Dark: 'rgb(28, 28, 30)',
  black: 'rgb(0, 0, 0)',

  redLight: 'rgb(255, 59, 48)',
  redDark: 'rgb(255, 69, 58)',

  orangeLight: 'rgb(255, 149, 0)',
  orangeDark: 'rgb(255, 159, 10)',

  yellowLight: 'rgb(255, 204, 0)',
  yellowDark: 'rgb(255, 214, 10)',

  greenLight: 'rgb(52, 199, 89)',
  greenDark: 'rgb(48, 209, 88)',

  tealLight: 'rgb(90, 200, 250)',
  tealDark: 'rgb(100, 210, 255)',

  blueLight: 'rgb(0, 122, 255)',
  blueDark: 'rgb(10, 132, 255)',

  indigoLight: 'rgb(88, 86, 214)',
  indigoDark: 'rgb(94, 92, 230)',

  purpleLight: 'rgb(175, 82, 222)',
  purpleDark: 'rgb(191, 90, 242)',

  pinkLight: 'rgb(255, 45, 85)',
  pinkDark: 'rgb(255, 55, 98)',

  reactColor: '#61dafb',
  javascriptColor: '#fcdc00',

  // Dracula Specific Colors
  draculaBackground: 'rgb(40, 42, 54)',
  draculaCurrentLine: 'rgb(68, 71, 90)',
  draculaForeground: 'rgb(248, 248, 242)',
  draculaComment: 'rgb(98, 114, 164)',
  draculaCyan: 'rgb(139, 233, 253)',
  draculaGreen: 'rgb(80, 250, 123)',
  draculaOrange: 'rgb(255, 184, 108)',
  draculaPink: 'rgb(255, 121, 198)',
  draculaPurple: 'rgb(189, 147, 249)',
  draculaRed: 'rgb(255, 85, 85)',
  draculaYellow: 'rgb(241, 250, 140)',

  // Monokai Specific Colors
  monokaiPink: '#F92672',
  monokaiOrange: '#FD971F',
  monokaiYellow: '#E6DB74',
  monokaiGreen: '#A6E22E',
  monokaiBlue: '#66D9EF',
  monokaiPurple: '#AE81FF',
  monokaiBlack: '#272822',
  monokaiWhite: '#D6D6D6',
  monokaiComment: '#797979',
  monokaiBackground: '#2E2E2E',
};

export const light = {
  alwaysBlack: colors.black,
  alwaysWhite: colors.white,
  background: colors.systemGray6Light,
  background2: colors.white,
  text: colors.black,
  textInverse: colors.white,
  systemGray: colors.systemGray,
  systemGray2: colors.systemGray2Light,
  systemGray3: colors.systemGray3Light,
  systemGray4: colors.systemGray4Light,
  systemGray5: colors.systemGray5Light,
  systemGray6: colors.systemGray6Light,
  red: colors.redLight,
  orange: colors.orangeLight,
  yellow: colors.yellowLight,
  green: colors.greenLight,
  teal: colors.tealLight,
  blue: colors.blueLight,
  indigo: colors.indigoLight,
  purple: colors.purpleLight,
  pink: colors.pinkLight,
  react: colors.reactColor,
  javascript: colors.javascriptColor,
};

export const dark = {
  alwaysBlack: colors.black,
  alwaysWhite: colors.white,
  background: colors.black,
  background2: colors.systemGray6Dark,
  text: colors.white,
  textInverse: colors.black,
  systemGray: colors.systemGray,
  systemGray2: colors.systemGray2Dark,
  systemGray3: colors.systemGray3Dark,
  systemGray4: colors.systemGray4Dark,
  systemGray5: colors.systemGray5Dark,
  systemGray6: colors.systemGray6Dark,
  red: colors.redDark,
  orange: colors.orangeDark,
  yellow: colors.yellowDark,
  green: colors.greenDark,
  teal: colors.tealDark,
  blue: colors.blueDark,
  indigo: colors.indigoDark,
  purple: colors.purpleDark,
  pink: colors.pinkDark,
  react: colors.reactColor,
  javascript: colors.javascriptColor,
};

export const dracula = {
  alwaysBlack: colors.draculaBackground,
  alwaysWhite: colors.draculaForeground,
  background: colors.draculaBackground,
  background2: colors.draculaCurrentLine,
  text: colors.draculaForeground,
  textInverse: colors.draculaBackground,
  systemGray: colors.draculaComment,
  systemGray2: colors.draculaComment,
  systemGray3: colors.draculaComment,
  systemGray4: colors.draculaCurrentLine,
  systemGray5: colors.draculaComment,
  systemGray6: colors.draculaCurrentLine,
  red: colors.draculaRed,
  orange: colors.draculaOrange,
  yellow: colors.draculaYellow,
  green: colors.draculaGreen,
  teal: colors.draculaCyan,
  blue: colors.draculaCyan,
  indigo: colors.draculaPurple,
  purple: colors.draculaPurple,
  pink: colors.draculaPink,
  react: colors.reactColor,
  javascript: colors.javascriptColor,
};

export const monokai = {
  alwaysBlack: colors.monokaiBlack,
  alwaysWhite: colors.monokaiWhite,
  background: colors.monokaiBlack,
  background2: colors.monokaiBackground,
  text: colors.monokaiWhite,
  textInverse: colors.monokaiBlack,
  systemGray: colors.monokaiComment,
  systemGray2: colors.monokaiComment,
  systemGray3: colors.monokaiComment,
  systemGray4: colors.monokaiBackground,
  systemGray5: colors.monokaiComment,
  systemGray6: colors.monokaiBackground,
  red: colors.monokaiPink,
  orange: colors.monokaiOrange,
  yellow: colors.monokaiYellow,
  green: colors.monokaiGreen,
  teal: colors.monokaiGreen,
  blue: colors.monokaiBlue,
  indigo: colors.monokaiPurple,
  purple: colors.monokaiPurple,
  pink: colors.monokaiPink,
  react: colors.reactColor,
  javascript: colors.javascriptColor,
};
