name: QA Checks
on:
  push:
    branches:
      -  '**'
  pull_request:
    branches:
      - main
jobs:
  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 24
      - name: Install Dependencies
        run: npm ci
      - name: Run Prettier
        run: npm run prettier
  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 24
      - name: Install Dependencies
        run: npm ci
      - name: Run ESLint
        run: npm run lint
  # jest:
  #   name: Jest
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Install NodeJS
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: 24
  #     - name: Install Dependencies
  #       run: npm ci
  #     - name: Run Jest
  #       run: npm run test
